version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm i npm@latest -g
      - pip install --upgrade pip
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - npm run generate
  post_build:
    commands:
      - ls -la
      - aws s3 sync ./dist s3://$S3_BUCKET
